swagger-ui:
   image: swaggerapi/swagger-ui
   container_name: swagger_ui_container
   ports:
      - "80:8080"
   volumes:
      - ./doc:/usr/share/nginx/html/doc
   environment:
      API_URL: doc/auth.yaml
